import type { Metadata } from "next";
import { MOCK_TOKYO_ITINERARY } from "@/lib/mock-data";

interface Props {
  params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const id = params.id;

  // Only the hardcoded demo trip has a stable, SSR-renderable identity;
  // every other /trip/[id] is a session-scoped or share-ID-scoped view
  // whose data isn't available at render time, so we deliberately leave
  // those noindex.
  if (id === "demo" || id === "tokyo-demo-5d") {
    const it = MOCK_TOKYO_ITINERARY;
    const days = it.days?.length ?? 0;
    const title = `Your ${days}-day ${it.destination} itinerary`;
    const description = `A sample ${days}-day ${it.destination} trip generated by Daytrip — day-by-day plan with food, culture, and hidden corners. Generate your own personalized version in seconds.`;
    return {
      title,
      description,
      alternates: { canonical: "/trip/demo" },
      openGraph: {
        title,
        description,
        type: "article",
        url: "/trip/demo",
        images: [
          {
            url: "/opengraph-image",
            width: 1200,
            height: 630,
            alt: title,
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title,
        description,
        images: ["/opengraph-image"],
      },
    };
  }

  return {
    title: "Your trip",
    description:
      "A personalized AI-generated travel itinerary from Daytrip.",
    robots: { index: false, follow: false },
  };
}

export default function TripLayout({ children }: { children: React.ReactNode }) {
  return children;
}
