import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-cream-100">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-cream-100/90 backdrop-blur-sm border-b border-cream-200">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="font-serif text-2xl text-terracotta-500 font-semibold">
            Daytrip
          </Link>
          <Link href="/" className="text-body-sm text-charcoal-800 hover:text-terracotta-500 transition-colors">
            Back to home
          </Link>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 pt-32 pb-20">
        <h1 className="font-serif text-display text-charcoal-900 mb-4">Terms of Service</h1>
        <p className="text-body text-charcoal-800/60 mb-12">Last updated: January 2024</p>

        <div className="font-sans text-body-lg text-charcoal-800 space-y-6">
          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Acceptance of Terms
          </h2>
          <p>
            By using Daytrip, you agree to these terms of service. If you do not agree,
            please do not use our service.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Service Description
          </h2>
          <p>
            Daytrip provides AI-generated travel itineraries for informational and planning
            purposes. While we strive for accuracy, itineraries are generated by artificial
            intelligence and should be verified before making travel arrangements.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Booking and Third Parties
          </h2>
          <p>
            Daytrip facilitates connections to third-party booking services. We are not
            responsible for the services, pricing, availability, or policies of these
            third-party providers. All bookings are subject to the terms of the respective
            provider.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Affiliate Disclosure
          </h2>
          <p>
            Daytrip earns commissions from bookings made through affiliate links in our
            itineraries. This does not affect the price you pay. Our recommendations are
            generated by AI based on quality and relevance, not commission rates.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Limitation of Liability
          </h2>
          <p>
            Daytrip is provided &ldquo;as is&rdquo; without warranties. We are not liable for
            any damages arising from the use of our service, including but not limited to
            inaccurate recommendations, booking issues, or travel disruptions.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            User Content
          </h2>
          <p>
            By sharing an itinerary via public link, you grant Daytrip permission to display
            that itinerary publicly. You may delete shared itineraries at any time.
          </p>

          <h2 className="font-serif text-heading-xl text-charcoal-900 mt-8 mb-4">
            Changes to Terms
          </h2>
          <p>
            We may update these terms from time to time. Continued use of Daytrip after
            changes constitutes acceptance of the updated terms.
          </p>
        </div>
      </article>
    </main>
  );
}
